// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Antmicro.Renode.Peripherals.CPU.GuestProfiling.ProtoBuf
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TrackDescriptor : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uuid")]
        public ulong Uuid
        {
            get { return __pbn__Uuid.GetValueOrDefault(); }
            set { __pbn__Uuid = value; }
        }
        public bool ShouldSerializeUuid() => __pbn__Uuid != null;
        public void ResetUuid() => __pbn__Uuid = null;
        private ulong? __pbn__Uuid;

        [global::ProtoBuf.ProtoMember(2, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(8, Name = @"counter")]
        public CounterDescriptor Counter { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class CounterDescriptor : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TrackEvent : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(23, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(9)]
        [global::System.ComponentModel.DefaultValue(Type.TypeUnspecified)]
        public Type type
        {
            get { return __pbn__type ?? Type.TypeUnspecified; }
            set { __pbn__type = value; }
        }
        public bool ShouldSerializetype() => __pbn__type != null;
        public void Resettype() => __pbn__type = null;
        private Type? __pbn__type;

        [global::ProtoBuf.ProtoMember(11, Name = @"track_uuid")]
        public ulong TrackUuid
        {
            get { return __pbn__TrackUuid.GetValueOrDefault(); }
            set { __pbn__TrackUuid = value; }
        }
        public bool ShouldSerializeTrackUuid() => __pbn__TrackUuid != null;
        public void ResetTrackUuid() => __pbn__TrackUuid = null;
        private ulong? __pbn__TrackUuid;

        [global::ProtoBuf.ProtoMember(30, Name = @"counter_value")]
        public long CounterValue
        {
            get { return __pbn__counter_value_field.Is(30) ? __pbn__counter_value_field.Int64 : default(long); }
            set { __pbn__counter_value_field = new global::ProtoBuf.DiscriminatedUnion64(30, value); }
        }
        public bool ShouldSerializeCounterValue() => __pbn__counter_value_field.Is(30);
        public void ResetCounterValue() => global::ProtoBuf.DiscriminatedUnion64.Reset(ref __pbn__counter_value_field, 30);

        private global::ProtoBuf.DiscriminatedUnion64 __pbn__counter_value_field;

        [global::ProtoBuf.ProtoMember(44, Name = @"double_counter_value")]
        public double DoubleCounterValue
        {
            get { return __pbn__counter_value_field.Is(44) ? __pbn__counter_value_field.Double : default(double); }
            set { __pbn__counter_value_field = new global::ProtoBuf.DiscriminatedUnion64(44, value); }
        }
        public bool ShouldSerializeDoubleCounterValue() => __pbn__counter_value_field.Is(44);
        public void ResetDoubleCounterValue() => global::ProtoBuf.DiscriminatedUnion64.Reset(ref __pbn__counter_value_field, 44);

        [global::ProtoBuf.ProtoContract()]
        public enum Type
        {
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_UNSPECIFIED")]
            TypeUnspecified = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SLICE_BEGIN")]
            TypeSliceBegin = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_SLICE_END")]
            TypeSliceEnd = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_INSTANT")]
            TypeInstant = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"TYPE_COUNTER")]
            TypeCounter = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TracePacket : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(8, Name = @"timestamp")]
        public ulong Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp() => __pbn__Timestamp != null;
        public void ResetTimestamp() => __pbn__Timestamp = null;
        private ulong? __pbn__Timestamp;

        [global::ProtoBuf.ProtoMember(11, Name = @"track_event")]
        public TrackEvent TrackEvent
        {
            get { return __pbn__data.Is(11) ? ((TrackEvent)__pbn__data.Object) : default(TrackEvent); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(11, value); }
        }
        public bool ShouldSerializeTrackEvent() => __pbn__data.Is(11);
        public void ResetTrackEvent() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 11);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__data;

        [global::ProtoBuf.ProtoMember(60, Name = @"track_descriptor")]
        public TrackDescriptor TrackDescriptor
        {
            get { return __pbn__data.Is(60) ? ((TrackDescriptor)__pbn__data.Object) : default(TrackDescriptor); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(60, value); }
        }
        public bool ShouldSerializeTrackDescriptor() => __pbn__data.Is(60);
        public void ResetTrackDescriptor() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 60);

        [global::ProtoBuf.ProtoMember(36, Name = @"synchronization_marker")]
        public byte[] SynchronizationMarker
        {
            get { return __pbn__data.Is(36) ? ((byte[])__pbn__data.Object) : default(byte[]); }
            set { __pbn__data = new global::ProtoBuf.DiscriminatedUnionObject(36, value); }
        }
        public bool ShouldSerializeSynchronizationMarker() => __pbn__data.Is(36);
        public void ResetSynchronizationMarker() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__data, 36);

        [global::ProtoBuf.ProtoMember(10, Name = @"trusted_packet_sequence_id")]
        public uint TrustedPacketSequenceId
        {
            get { return __pbn__TrustedPacketSequenceId.GetValueOrDefault(); }
            set { __pbn__TrustedPacketSequenceId = value; }
        }
        public bool ShouldSerializeTrustedPacketSequenceId() => __pbn__TrustedPacketSequenceId != null;
        public void ResetTrustedPacketSequenceId() => __pbn__TrustedPacketSequenceId = null;
        private uint? __pbn__TrustedPacketSequenceId;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Trace : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"packets")]
        public global::System.Collections.Generic.List<TracePacket> Packets { get; } = new global::System.Collections.Generic.List<TracePacket>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
